/**
 * Walk To Fly API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 區域OutputModel
 */
export interface AreaOutputModel { 
    /**
     * 鄉鎮縣市區Id
     */
    id?: number;
    /**
     * 鄉鎮縣市區名稱
     */
    name?: string;
    /**
     * RF:縣市Id
     */
    citiId?: string;
}