/**
 * 走到飛 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 取得會員資料參數
 */
export interface GetMemberParameter { 
    /**
     * 會員Id
     */
    memberId?: string;
    /**
     * 密碼
     */
    password?: string;
}