/**
 * 走到飛 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 會員修改密碼參數
 */
export interface MemberEditPasswordParameter { 
    /**
     * 會員Id
     */
    memberId?: string;
    /**
     * 舊密碼
     */
    oldPassword?: string;
    /**
     * 新密碼
     */
    newPassword?: string;
}