/**
 * Walk To Fly API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SmallMenuOutputModel } from './smallMenuOutputModel';

/**
 * 選單OutputModel
 */
export interface MenuOutputModel { 
    /**
     * 大功能Id
     */
    functionId?: number;
    /**
     * 大功能名稱
     */
    functionName?: string;
    /**
     * 大功能中文名稱
     */
    functionChineseName?: string;
    /**
     * 附屬功能列表
     */
    smallMenuDtos?: Array<SmallMenuOutputModel>;
}