/**
 * Walk To Fly API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Result } from './result';

/**
 * API成功類別
 */
export interface ResultSuccessOutputModel { 
    /**
     * API序號
     */
    id?: string;
    /**
     * API版本
     */
    apiVersion?: string;
    /**
     * 方法名稱
     */
    method?: string;
    data?: Result;
}