/**
 * 走到飛 API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { SystemFunctionOutputModel } from './systemFunctionOutputModel';

/**
 * API成功類別
 */
export interface SystemFunctionOutputModelIEnumerableSuccessOutputModel { 
    /**
     * API序號
     */
    id?: string;
    /**
     * API版本
     */
    apiVersion?: string;
    /**
     * 方法名稱
     */
    method?: string;
    /**
     * 回傳內容
     */
    data?: Array<SystemFunctionOutputModel>;
}