/**
 * Walk To Fly API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 附屬功能OutputModel
 */
export interface SystemFunctionDetailOutputModel { 
    /**
     * 附屬功能Id
     */
    functionDetailId?: number;
    /**
     * 大功能Id RF:SystemFunction.FunctionId
     */
    functionId?: number;
    /**
     * 附屬功能名稱
     */
    functionDetailName?: string;
    /**
     * 附屬功能中文名稱
     */
    functionDetailChineseName?: string;
    /**
     * 備註
     */
    remark?: string;
    /**
     * 排序
     */
    sort?: number;
    /**
     * 是否啟用
     */
    enableFlag?: boolean;
}