/**
 * Walk To Fly API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: v1
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

/**
 * 角色OutputModel
 */
export interface SystemRoleUserOutputModel { 
    /**
     * 角色Id
     */
    roleUserId?: number;
    /**
     * 角色名稱
     */
    roleUserName?: string;
}